spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/root?schema=public
    username: root
    password: root

flyway:
  url: jdbc:postgresql://localhost:5432/root?schema=public
  user: ${spring.r2dbc.username}
  password: ${spring.r2dbc.password}
  baseline-on-migrate: true
  locations: 'filesystem:fixed-data-domain/src/main/resources/db/migration'
  schemas: 'public'

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  error:
    include-stacktrace: on_param